# Generated by Django 4.1.13 on 2024-02-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0002_chatlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatlog",
            name="answer",
            field=models.CharField(max_length=2000),
        ),
    ]
