# Generated by Django 4.1.13 on 2024-01-29 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_vehicle"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="product",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
            ),
        ),
    ]
