# Generated by Django 4.1.13 on 2024-02-05 02:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_file_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="user",
        ),
    ]
