# Generated by Django 4.1.13 on 2024-02-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_product_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="model",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
