# Generated by Django 4.1.13 on 2024-02-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_product_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="filetype",
            field=models.CharField(default="txt", max_length=6),
            preserve_default=False,
        ),
    ]
